version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "chore"
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/opencode/.config/opencode"
    schedule:
      interval: "weekly"
    labels:
      - "chore"
      - "dependencies"
