#!/bin/zsh
# Generated by scripts/build-hyper-config.mjs. Fixed actions only; never eval a query.
set -eu
workflow_dir="${0:A:h}"
launch() {
  if [[ "${HYPER_DRY_RUN:-0}" == 1 ]]; then
    printf '%s\n' "$@"
  else
    /usr/bin/open "$@"
  fi
}
case "${1:-}" in
  'app:chrome') launch -b 'com.google.Chrome' ;;
  'app:ghostty') launch -b 'com.mitchellh.ghostty' ;;
  'app:finder') launch -b 'com.apple.finder' ;;
  'app:codex') launch -b 'com.openai.codex' ;;
  'app:cursor') launch -b 'com.todesktop.230313mzl4w4u92' ;;
  'app:claude') launch -b 'com.anthropic.claudefordesktop' ;;
  'app:amp') launch -b 'com.ampcode.amp.macos' ;;
  'app:obsidian') launch -b 'md.obsidian' ;;
  'app:edge') launch -b 'com.microsoft.edgemac' ;;
  'app:teams') launch -b 'com.microsoft.teams2' ;;
  'app:slack') launch -b 'com.tinyspeck.slackmacgap' ;;
  'app:word') launch -b 'com.microsoft.Word' ;;
  'app:excel') launch -b 'com.microsoft.Excel' ;;
  'app:powerpoint') launch -b 'com.microsoft.Powerpoint' ;;
  'app:safari') launch -b 'com.apple.Safari' ;;
  'app:finalcut') launch -b 'com.apple.FinalCut' ;;
  'app:motion') launch -b 'com.apple.motionapp' ;;
  'app:compressor') launch -b 'com.apple.Compressor' ;;
  'layout:Work') launch -g 'dockflow://switch?id=01BAE638-6C40-47C3-A97D-F52F4CB3A9A3'
    launch -g 'rectangle-pro://execute-layout?name=Work' ;;
  'layout:Work Balanced') launch -g 'dockflow://switch?id=01BAE638-6C40-47C3-A97D-F52F4CB3A9A3'
    launch -g 'rectangle-pro://execute-layout?name=Work%20Balanced' ;;
  'layout:Office') launch -g 'dockflow://switch?id=01BAE638-6C40-47C3-A97D-F52F4CB3A9A3'
    launch -g 'rectangle-pro://execute-layout?name=Office' ;;
  'layout:Present') launch -g 'dockflow://switch?id=01BAE638-6C40-47C3-A97D-F52F4CB3A9A3'
    launch -g 'rectangle-pro://execute-layout?name=Present' ;;
  'layout:Code') launch -g 'dockflow://switch?id=D405D7FD-6999-4EC7-8428-7E361C0D51A2'
    launch -g 'rectangle-pro://execute-layout?name=Code' ;;
  'layout:Code Balanced') launch -g 'dockflow://switch?id=D405D7FD-6999-4EC7-8428-7E361C0D51A2'
    launch -g 'rectangle-pro://execute-layout?name=Code%20Balanced' ;;
  'layout:Terminal') launch -g 'rectangle-pro://execute-layout?name=Terminal' ;;
  'layout:Agents') launch -g 'dockflow://switch?id=D405D7FD-6999-4EC7-8428-7E361C0D51A2'
    launch -g 'rectangle-pro://execute-layout?name=Agents' ;;
  'layout:Zen') launch -g 'dockflow://switch?id=48FF680F-04C9-4EC1-8E23-2E6BC88A3702'
    launch -g 'rectangle-pro://execute-layout?name=Zen' ;;
  'layout:Default') launch -g 'dockflow://switch?id=68FBB9EF-7C52-46B1-9483-E0A6F625ED1E'
    launch -g 'rectangle-pro://execute-layout?name=Default' ;;
  'window:maximize') launch -g 'rectangle-pro://execute-action?name=maximize' ;;
  'window:restore') launch -g 'rectangle-pro://execute-action?name=restore' ;;
  'window:left-half') launch -g 'rectangle-pro://execute-action?name=left-half' ;;
  'window:right-half') launch -g 'rectangle-pro://execute-action?name=right-half' ;;
  'window:first-third') launch -g 'rectangle-pro://execute-action?name=first-third' ;;
  'window:center-third') launch -g 'rectangle-pro://execute-action?name=center-third' ;;
  'window:last-third') launch -g 'rectangle-pro://execute-action?name=last-third' ;;
  'window:first-two-thirds') launch -g 'rectangle-pro://execute-action?name=first-two-thirds' ;;
  'window:last-two-thirds') launch -g 'rectangle-pro://execute-action?name=last-two-thirds' ;;
  'window:prev-space') launch -g 'rectangle-pro://execute-action?name=prev-space' ;;
  'window:next-space') launch -g 'rectangle-pro://execute-action?name=next-space' ;;
  'window:previous-display') launch -g 'rectangle-pro://execute-action?name=previous-display' ;;
  'window:next-display') launch -g 'rectangle-pro://execute-action?name=next-display' ;;
  guide) launch "$workflow_dir/guide.html" ;;
  *) printf '%s\n' 'Unknown Hyper action. Open Hyper+Space and choose an item.' >&2; exit 64 ;;
esac
